options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'node:20'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        npm install
        npm run build

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'asia-southeast2-docker.pkg.dev/foskin-nendy/foskin-nendy-docker/foskin-spa:latest'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia-southeast2-docker.pkg.dev/foskin-nendy/foskin-nendy-docker/foskin-spa:latest'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run deploy react-app \
          --image asia-southeast2-docker.pkg.dev/foskin-nendy/foskin-nendy-docker/foskin-spa:latest \
          --platform managed \
          --region YOUR_REGION \
          --allow-unauthenticated
